CREATE TABLE IF NOT EXISTS dentista (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    cro VARCHAR(10) NOT NULL UNIQUE,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);